## NumPy Interview Questions
---
### Question 1: Creating a Range Array

How would you create a NumPy array containing all even integers from 10 to 50 (inclusive)?

**Solution:**

In [2]:
import numpy as np

res = np.arange(10, 51, 2)

print(res)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### Question 2: Reshaping an Array

Create a 1D NumPy array with 12 sequential integers starting from 1. Then, reshape it into a 4x3 matrix.

**Solution:**

In [12]:
x = np.linspace(1, 12, 12)
x = np.arange(1, 13, 1)

x_matrix = x.reshape(4, 3)

print(x_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Question 3: Boolean Indexing

Given the array `data = np.array([5, 15, 25, 35, 45, 55])`, write a single line of code to select all elements that are greater than 20 but less than 50.

**Solution:**

In [15]:
data = np.array([5, 15, 25, 35, 45, 55])

res = data[(data > 20) & (data < 50)]

# res = data[data > 20 & data < 50] is wrong because "&"" has higher precedence, Python tries to evaluate the expression 20 & data first.

print(res)

[25 35 45]


### Question 4: Aggregation Along an Axis

Given the 2D array `matrix = np.array([[10, 20, 30], [40, 50, 60]])`, calculate the sum of the elements for each column.

**Solution:**

In [ ]:
# my solution
matrix = np.array([[10, 20, 30], [40, 50, 60]])

col_sum = np.zeros(len(matrix[0]))

for row in matrix:
    col_sum += row

print(col_sum)

# alternative solution
matrix = np.array([[10, 20, 30], [40, 50, 60]])
column_sums = np.sum(matrix, axis=0)
print(column_sums)

[50. 70. 90.]
[50 70 90]


### Question 5: Combining Arrays

You have two NumPy arrays: `a = np.array([[1, 1], [2, 2]])` and `b = np.array([[3, 3], [4, 4]])`. How do you stack them horizontally to create a single array?

**Solution:**

In [ ]:
a = np.array([[1, 1], [2, 2]])
b = np.array([[3, 3], [4, 4]])

ab = np.hstack((a, b))
print(ab)

print("--------------")

ab = np.concatenate((a, b), axis=1)
print(ab)

[[1 1 3 3]
 [2 2 4 4]]
--------------
[[1 1 3 3]
 [2 2 4 4]]


### Question 6: Array Creation with Specific Data Types

Create a 3x3 NumPy array filled with ones, ensuring the data type is integer.

**Solution:**

In [29]:
import numpy as np
ones_int_array = np.ones((3, 3), dtype=int)
print(ones_int_array)

print("--------------")

ones_int_array = np.ones((3, 3))
print(ones_int_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
--------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Question 7: Slicing a 2D Array

Given the array `arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`, extract the sub-array `[[6, 7], [10, 11]]`.

**Solution:**

In [ ]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

sub_array = arr2d[1:3, 1:3]
print(sub_array)


[[ 6  7]
 [10 11]]


### Question 8: Universal Functions (ufunc)

Given the array `arr = np.array([1, 4, 9, 16])`, how would you compute the square root of each element?

**Solution:**

In [8]:
arr = np.array([1, 4, 9, 16])

arr_sqr = np.sqrt(arr)

print(arr_sqr)

print(np.exp(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


### Question 9: Array Inspection

You are given a NumPy array named `my_array`. How would you find its dimensions, total number of elements, and data type?

**Solution:**

In [9]:
import numpy as np
my_array = np.random.randint(0, 100, size=(5, 4)) # Example array
shape = my_array.shape
size = my_array.size
dtype = my_array.dtype
print(f"Shape: {shape}, Size: {size}, Dtype: {dtype}")

Shape: (5, 4), Size: 20, Dtype: int32


### Question 10: Scalar Operations

You have the array `arr = np.array([10, 20, 30])`. How do you subtract 5 from every element in the array?

**Solution:**

In [10]:
import numpy as np
arr = np.array([10, 20, 30])
result = arr - 5
print(result)

[ 5 15 25]
